// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaBooking.Infrastructure.Data;

#nullable disable

namespace VillaBooking.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240413071254_Add_Amenity_Table")]
    partial class Add_Amenity_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("VillaBooking.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Occupancy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Sqft")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(38),
                            Description = "The superior services and facilities offered at Maitri Retreat will make for a memorable stay. Parking is provided free of charge for guests. Smoking may only take place in restricted designated areas. Guests are guaranteed a comfortable stay while at Maitri Retreat. To enhance your stay, some rooms at the bungalow come with linen service and air conditioning. The bungalow's in-room entertainment is second to none, with television and cable TV provided to guests in select rooms. You may be assured to know that instant coffee and instant tea are available in some select rooms. You can stay fresh and clean with toiletries and towels provided in some of the guest bathrooms.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550,
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(39)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(41),
                            Description = "Athithi homestay is a place with aesthetic ambience and offers a beautiful view of the garden and mountains along with mesmerizing view of the sunset. Homestay, where elegance and comfort meet to create an unforgettable experience. Situated in a serene and picturesque location, our villa offers a perfect retreat for those seeking tranquility and relaxation. You'll be greeted by a spacious and beautifully designed living area that exudes charm and sophistication. The interior is tastefully decorated with a blend of modern aesthetics and traditional elements, creating a warm and inviting atmosphere. Our friendly and attentive staff is dedicated to making your stay exceptional. From housekeeping services to arranging transportation or organizing excursions, we strive to meet your every need. Whether you're planning a family vacation, a romantic getaway, or a retreat with friends, our villa homestay provides the perfect setting for an unforgettable experience. Immerse yourself in luxury, comfort, and natural beauty, and create memories that will last a lifetime. Rooms are elegantly furnished and offer a serene atmosphere for a peaceful stay. They are equipped with either a king-size bed or twin beds, depending on your preference. The rooms are adorned with tasteful decor and provide ample space for relaxation.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550,
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(42)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(43),
                            Description = "It's rare to find a place that's both historic and one of a kind. A 150-year old heritage property with its old world charm thoughtfully embellished with modern facilities, invites you to relax, unwind and leave totally rejuvenated.Set amidst a sprawling field of greenery.The chirping of the birds to wake you in the morning and enjoy the beauty of nature as butterflies float around you.Go on a hike, or sit by the fire. Meditate or simply watch the sunset. Come and Make Happy Memories! The space The property is stretched to 10+Acres with Forest Area, Livestock Areas, Garden Areas + Living Areas. The Living Areas include the Heritage Building with the ground floor accessible to guests and a Cottage accessible to guests who have booked the Cottage rooms. The Living Area also consists of a traditional wood fire kitchen. Guest access The Dining, Library, the Lounge, the recreational garden areas and the selected farming areas is also accessible to the Guests.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750,
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(44)
                        });
                });

            modelBuilder.Entity("VillaBooking.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VillaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(116),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(117),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(118),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(118),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(119),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(120),
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(120),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(121),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(122),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(122),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(123),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(123),
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(124),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(124),
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(125),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(125),
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            CreatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(126),
                            UpdatedDateTime = new DateTime(2024, 4, 13, 7, 12, 54, 342, DateTimeKind.Utc).AddTicks(126),
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("VillaBooking.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("VillaBooking.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
